name: ckan-client-py actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6
          poetry_version: 1.1.0
          args: install
      - name: Run tests
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6
          poetry_version: 1.1.0
          args: run pytest
